trigger:
- main
pr:
  drafts: false
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build Stage
   displayName: Build
   jobs:
     - job: Build
       displayName: Build App
       steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
        - task: CopyFiles@2
          displayName: 'Copyfiles to artifact staging directory'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/target/*.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            ArtifactName: 'drop'
            PathtoPublish: '$(build.artifactstagingdirectory)'

 - stage: Deploy
   displayName: Build
   dependsOn: Build Stage
   condition: and(succeeded(),eq(variables['Build.SourceBranch'], 'refs/heads/main'))
   jobs:
    - job: Deploy
      displayName: Deployment on Azure
      steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Azure subscription 1 (95769b1d-2152-41ad-a8e7-0b5b80d2b9bb)'
          appType: 'webApp'
          WebAppName: 'academia-digital-api-ms'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.jar'
          enableCustomDeployment: true
          DeploymentType: 'webDeploy'

